#!/usr/bin/env python3
"""
Fit the default 4x4 B2 cluster isotropic Vecchia on pre-generated July
simulation assets.

Created 2026-05-24.

What this script does:
  1. Load the real-location-like July ST simulation pickles generated by
     simulate_data/generate_july_st_circulant_real_locations_2022_2025.py.
  2. Treat each day asset as eight independent pure-space replicates that share
     one isotropic Matérn covariance parameter set.
  3. Fit the 4x4 cluster max-min pure-space model from
     kernels_space_iso_cluster_052426.py with B=2 neighbor blocks by default.
  4. Append one compact row per fit and refresh running CSV/TXT summaries.

No new data are simulated here.  This is only a fitting/optimization comparison.

Truth convention:
  The simulation truth is anisotropic in latitude/longitude, while both tested
  modules are isotropic.  For scoring the fitted isotropic range, this script
  uses sqrt(range_lat * range_lon) as the reference isotropic range.
"""

from __future__ import annotations

import argparse
import csv
import gc
import json
import math
import os
import pickle
import random
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F


AMAREL_SRC = "/home/jl2815/tco"
LOCAL_SRC = "/Users/joonwonlee/Documents/GEMS_TCO-1/src"
SRC = AMAREL_SRC if os.path.exists(AMAREL_SRC) else LOCAL_SRC
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from GEMS_TCO.kernels_space_iso_cluster_052426 import ClusterSpaceIsoTrendVecchiaFit


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DTYPE = torch.float64
ROUND_DECIMALS = 6
DELTA_LAT_BASE = 0.044
DELTA_LON_BASE = 0.063
T_STEPS = 8

PARAMS = ["sigmasq", "range", "nugget"]
ROW_COLUMNS = [
    "fit_id",
    "sim_id",
    "seed",
    "asset_year",
    "asset_day_idx",
    "asset_first_key",
    "data_kind",
    "model_family",
    "spec_name",
    "smooth",
    "mean_design",
    "cluster_block_shape",
    "cluster_neighbor_blocks",
    "n_cond_points_nominal",
    "n_valid",
    "n_grid",
    "valid_by_t",
    "loss",
    "converged",
    "fit_steps",
    "precompute_s",
    "fit_s",
    "total_s",
    "n_batches",
    "n_target_blocks",
    "n_target_points",
    "max_points_per_cluster",
    "median_cond_points",
    "max_cond_points",
    "median_target_size",
    "overall_rmsre",
    "median_abs_error",
    *[f"est_{p}" for p in PARAMS],
    *[f"abs_error_{p}" for p in PARAMS],
    *[f"{p}_re" for p in PARAMS],
    "error",
]


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def parse_range(s: str) -> list[float]:
    vals = [float(x.strip()) for x in str(s).split(",") if x.strip()]
    if len(vals) != 2:
        raise argparse.ArgumentTypeError("range must look like min,max")
    return [min(vals), max(vals)]


def parse_int_list(s: str) -> list[int]:
    return [int(x.strip()) for x in str(s).split(",") if x.strip()]


def parse_years(s: str) -> list[int]:
    return parse_int_list(s)


def parse_block_shape(s: str) -> tuple[int, int]:
    vals = [int(x.strip()) for x in str(s).lower().replace("x", ",").split(",") if x.strip()]
    if len(vals) != 2:
        raise argparse.ArgumentTypeError("block shape must look like 4x4")
    return vals[0], vals[1]


def parse_day_idxs(s: str) -> list[int] | str:
    text = str(s).strip().lower()
    if text in {"all", "*"}:
        return "all"
    return parse_int_list(text)


def parse_gems_hour_key(key: str) -> pd.Timestamp | None:
    pat = r"^y(?P<yy>\d{2})m(?P<mm>\d{2})day(?P<dd>\d{2})_hm(?P<hh>\d{2}):(?P<minute>\d{2})$"
    match = re.match(pat, str(key))
    if not match:
        return None
    parts = {name: int(value) for name, value in match.groupdict().items()}
    return pd.Timestamp(
        year=2000 + parts["yy"],
        month=parts["mm"],
        day=parts["dd"],
        hour=parts["hh"],
        minute=parts["minute"],
        tz="UTC",
    )


def ordered_asset_keys(obj: dict[Any, Any]) -> list[Any]:
    parsed = []
    for key in obj:
        ts = parse_gems_hour_key(str(key))
        if ts is not None:
            parsed.append((ts, key))
    return [key for _, key in sorted(parsed)] if parsed else sorted(obj)


def asset_paths(sim_data_root: Path, year: int, data_kind: str) -> tuple[Path, Path]:
    year_dir = sim_data_root / f"{year}_july_st_circulant"
    prefix = f"sim_july{year}_st_circulant"
    return year_dir / f"{prefix}_{data_kind}.pkl", year_dir / f"{prefix}_truth.json"


def load_truth(truth_path: Path) -> dict[str, float]:
    if not truth_path.exists():
        raise FileNotFoundError(f"Missing simulation truth file: {truth_path}")
    raw = json.loads(truth_path.read_text(encoding="utf-8"))
    out = {
        "sigmasq": float(raw["sigmasq"]),
        "range_lat": float(raw["range_lat"]),
        "range_lon": float(raw["range_lon"]),
        "range": float(math.sqrt(float(raw["range_lat"]) * float(raw["range_lon"]))),
        "nugget": float(raw["nugget"]),
        "smooth": float(raw.get("smooth", 0.5)),
    }
    return out


def load_asset_map(path: Path) -> dict[Any, pd.DataFrame]:
    if not path.exists():
        raise FileNotFoundError(f"Missing pre-generated simulation pickle: {path}")
    with open(path, "rb") as f:
        obj = pickle.load(f)
    if not isinstance(obj, dict):
        raise TypeError(f"{path} must contain a dict of DataFrames")
    return obj


def grid_filtered_frame(df: pd.DataFrame, lat_range: list[float], lon_range: list[float]) -> pd.DataFrame:
    required = {"Latitude", "Longitude", "ColumnAmountO3"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"DataFrame missing required columns: {sorted(missing)}")
    out = df.copy()
    out["_grid_lat"] = pd.to_numeric(out["Latitude"], errors="coerce")
    out["_grid_lon"] = pd.to_numeric(out["Longitude"], errors="coerce")
    mask = (
        np.isfinite(out["_grid_lat"])
        & np.isfinite(out["_grid_lon"])
        & (out["_grid_lat"] >= min(lat_range))
        & (out["_grid_lat"] <= max(lat_range))
        & (out["_grid_lon"] >= min(lon_range))
        & (out["_grid_lon"] <= max(lon_range))
    )
    out = out.loc[mask].copy()
    out["_grid_lat_key"] = np.round(out["_grid_lat"].to_numpy(dtype=float), ROUND_DECIMALS)
    out["_grid_lon_key"] = np.round(out["_grid_lon"].to_numpy(dtype=float), ROUND_DECIMALS)
    return out


def build_master_grid(first_df: pd.DataFrame, lat_range: list[float], lon_range: list[float]) -> pd.DataFrame:
    first = grid_filtered_frame(first_df, lat_range, lon_range)
    master = (
        first[["_grid_lat_key", "_grid_lon_key", "_grid_lat", "_grid_lon"]]
        .drop_duplicates(["_grid_lat_key", "_grid_lon_key"])
        .sort_values(["_grid_lat", "_grid_lon"])
        .reset_index(drop=True)
    )
    if master.empty:
        raise ValueError("No grid rows left after lat/lon filtering.")
    return master


def build_regular_master_grid(lat_range: list[float], lon_range: list[float]) -> pd.DataFrame:
    lats = np.arange(min(lat_range), max(lat_range) + 1e-4, DELTA_LAT_BASE, dtype=float)
    lons = np.arange(min(lon_range), max(lon_range) + 1e-4, DELTA_LON_BASE, dtype=float)
    lats = np.round(lats, ROUND_DECIMALS)
    lons = np.round(lons, ROUND_DECIMALS)
    g_lat, g_lon = np.meshgrid(lats, lons, indexing="ij")
    master = pd.DataFrame({"_grid_lat": g_lat.ravel(), "_grid_lon": g_lon.ravel()})
    master["_grid_lat_key"] = np.round(master["_grid_lat"].to_numpy(dtype=float), ROUND_DECIMALS)
    master["_grid_lon_key"] = np.round(master["_grid_lon"].to_numpy(dtype=float), ROUND_DECIMALS)
    return master[["_grid_lat_key", "_grid_lon_key", "_grid_lat", "_grid_lon"]]


def align_to_master_grid(df: pd.DataFrame, master: pd.DataFrame, lat_range: list[float], lon_range: list[float]) -> pd.DataFrame:
    part = grid_filtered_frame(df, lat_range, lon_range)
    finite_y = np.isfinite(pd.to_numeric(part["ColumnAmountO3"], errors="coerce").to_numpy(dtype=float))
    part = part.assign(_finite_y=finite_y).sort_values("_finite_y", ascending=False)
    part = part.drop_duplicates(["_grid_lat_key", "_grid_lon_key"], keep="first")
    part = part.set_index(["_grid_lat_key", "_grid_lon_key"])
    idx = pd.MultiIndex.from_frame(master[["_grid_lat_key", "_grid_lon_key"]])
    aligned = part.reindex(idx).reset_index()
    aligned["_grid_lat"] = master["_grid_lat"].to_numpy(dtype=float)
    aligned["_grid_lon"] = master["_grid_lon"].to_numpy(dtype=float)
    return aligned


def tensor_from_aligned_frame(aligned: pd.DataFrame, t_idx: int, monthly_mean: float, center_response: bool) -> torch.Tensor:
    y = pd.to_numeric(aligned["ColumnAmountO3"], errors="coerce").to_numpy(dtype=float)
    if center_response:
        y = y - float(monthly_mean)

    if {"Source_Latitude", "Source_Longitude"}.issubset(aligned.columns):
        lat = pd.to_numeric(aligned["Source_Latitude"], errors="coerce").to_numpy(dtype=float)
        lon = pd.to_numeric(aligned["Source_Longitude"], errors="coerce").to_numpy(dtype=float)
    else:
        lat = aligned["_grid_lat"].to_numpy(dtype=float)
        lon = aligned["_grid_lon"].to_numpy(dtype=float)

    valid = np.isfinite(y) & np.isfinite(lat) & np.isfinite(lon)
    y = np.where(valid, y, np.nan)
    lat = np.where(valid, lat, np.nan)
    lon = np.where(valid, lon, np.nan)

    base = np.full((len(aligned), 4), np.nan, dtype=np.float64)
    base[:, 0] = lat
    base[:, 1] = lon
    base[:, 2] = y
    base[:, 3] = float(t_idx)
    base_tensor = torch.from_numpy(base).to(dtype=DTYPE)

    dummies = F.one_hot(torch.tensor([t_idx]), num_classes=T_STEPS).repeat(len(base_tensor), 1)
    dummies = dummies[:, 1:].to(DTYPE)
    return torch.cat([base_tensor, dummies], dim=1).contiguous()


def build_day_asset(
    sim_map: dict[Any, pd.DataFrame],
    year: int,
    day_idx: int,
    lat_range: list[float],
    lon_range: list[float],
    center_response: bool,
    master: pd.DataFrame,
    monthly_mean: float,
) -> dict[str, Any] | None:
    keys = ordered_asset_keys(sim_map)
    day_keys = keys[day_idx * T_STEPS : (day_idx + 1) * T_STEPS]
    if len(day_keys) < T_STEPS:
        return None

    source_map = {}
    valid_by_t = []
    for t_idx, key in enumerate(day_keys):
        aligned = align_to_master_grid(sim_map[key], master, lat_range, lon_range)
        tensor = tensor_from_aligned_frame(aligned, t_idx, monthly_mean, center_response)
        source_map[str(key)] = tensor
        valid_by_t.append(int(torch.isfinite(tensor[:, 2]).sum().item()))

    grid_coords_np = master[["_grid_lat", "_grid_lon"]].to_numpy(dtype=np.float64)
    return {
        "year": int(year),
        "day_idx": int(day_idx),
        "day_keys": [str(k) for k in day_keys],
        "source_map": source_map,
        "grid_coords_np": grid_coords_np,
        "n_grid": int(grid_coords_np.shape[0]),
        "monthly_mean": float(monthly_mean),
        "valid_by_t": valid_by_t,
    }


def build_asset_bank(args: argparse.Namespace) -> tuple[list[dict[str, Any]], dict[str, float]]:
    years = parse_years(args.years)
    requested_day_idxs = parse_day_idxs(args.day_idxs)
    bank: list[dict[str, Any]] = []
    truth_ref: dict[str, float] | None = None

    for year in years:
        pickle_path, truth_path = asset_paths(args.sim_data_root, year, args.data_kind)
        truth = load_truth(truth_path)
        if truth_ref is None:
            truth_ref = truth
        else:
            for key in ["sigmasq", "range_lat", "range_lon", "nugget", "smooth"]:
                if not np.isclose(truth_ref[key], truth[key]):
                    raise ValueError(f"Truth mismatch for {key}: {truth_ref[key]} vs {truth[key]} in {truth_path}")

        sim_map = load_asset_map(pickle_path)
        keys = ordered_asset_keys(sim_map)
        max_day_idx = len(keys) // T_STEPS - 1
        try:
            master = build_master_grid(sim_map[keys[0]], args.lat_range, args.lon_range)
            master_source = "generated_pickle_lat_lon"
        except Exception as exc:
            print(
                f"WARNING: could not build grid from generated pickle Latitude/Longitude ({exc!r}); "
                "falling back to native regular grid.",
                flush=True,
            )
            master = build_regular_master_grid(args.lat_range, args.lon_range)
            master_source = "native_regular_grid_fallback"

        month_vals = []
        for key in keys:
            aligned = align_to_master_grid(sim_map[key], master, args.lat_range, args.lon_range)
            month_vals.append(pd.to_numeric(aligned["ColumnAmountO3"], errors="coerce").to_numpy(dtype=float))
        monthly_mean = float(np.nanmean(np.concatenate(month_vals)))

        if requested_day_idxs == "all":
            day_idxs = list(range(max_day_idx + 1))
        else:
            day_idxs = [d for d in requested_day_idxs if d <= max_day_idx]

        print(
            f"Loaded {pickle_path} with {len(keys)} hours; usable day blocks={max_day_idx + 1}; "
            f"grid_source={master_source}, n_grid={len(master):,}",
            flush=True,
        )
        for day_idx in day_idxs:
            asset = build_day_asset(
                sim_map=sim_map,
                year=year,
                day_idx=day_idx,
                lat_range=args.lat_range,
                lon_range=args.lon_range,
                center_response=args.center_response,
                master=master,
                monthly_mean=monthly_mean,
            )
            if asset is None or sum(asset["valid_by_t"]) == 0:
                continue
            bank.append(asset)
            print(
                f"Prepared asset year={year} day_idx={day_idx} valid={asset['valid_by_t']}",
                flush=True,
            )
            if args.max_asset_days > 0 and len(bank) >= args.max_asset_days:
                break
        if args.max_asset_days > 0 and len(bank) >= args.max_asset_days:
            break

    if not bank:
        raise RuntimeError("No pre-generated day assets were loaded.")
    assert truth_ref is not None
    return bank, truth_ref


def init_params(truth: dict[str, float], rng: np.random.Generator, init_noise: float) -> list[torch.Tensor]:
    vals = [truth["sigmasq"], truth["range"], truth["nugget"]]
    logs = [math.log(max(float(v), 1e-12)) + float(rng.uniform(-init_noise, init_noise)) for v in vals]
    return [torch.tensor(v, device=DEVICE, dtype=DTYPE, requires_grad=True) for v in logs]


def backmap(raw: list[float]) -> dict[str, float]:
    return {
        "sigmasq": float(math.exp(raw[0])),
        "range": float(math.exp(raw[1])),
        "nugget": float(math.exp(raw[2])),
    }


def calculate_metrics(est: dict[str, float], truth: dict[str, float]) -> dict[str, float]:
    out = {}
    re_vals = []
    abs_vals = []
    for p in PARAMS:
        abs_err = abs(est[p] - truth[p])
        denom = abs(truth[p]) if abs(truth[p]) >= 0.01 else 1.0
        re = abs_err / denom
        out[f"abs_error_{p}"] = abs_err
        out[f"{p}_re"] = re
        re_vals.append(re)
        abs_vals.append(abs_err)
    out["overall_rmsre"] = float(np.sqrt(np.mean(np.asarray(re_vals, dtype=float) ** 2)))
    out["median_abs_error"] = float(np.median(abs_vals))
    return out


def fit_model(
    spec: dict[str, Any],
    source_map: dict[str, torch.Tensor],
    grid_coords_np: np.ndarray,
    truth: dict[str, float],
    args: argparse.Namespace,
    rng: np.random.Generator,
) -> dict[str, Any]:
    params = init_params(truth, rng, args.init_noise)
    smooth = float(truth.get("smooth", args.smooth_fallback))

    if spec["model_family"] != "cluster":
        raise ValueError(f"Only cluster B2 pure-space fits are active, got {spec['model_family']}")

    model = ClusterSpaceIsoTrendVecchiaFit(
        smooth=smooth,
        input_map=source_map,
        grid_coords=grid_coords_np,
        block_shape=args.cluster_block_shape,
        n_neighbor_blocks=int(spec["cluster_neighbor_blocks"]),
        target_chunk_size=int(args.cluster_target_chunk_size),
        min_target_points=int(args.min_target_points),
        mean_design=args.mean_design,
    )

    t0 = time.time()
    model.precompute_conditioning_sets()
    pre_s = time.time() - t0

    opt = model.set_optimizer(
        params,
        lr=1.0,
        max_iter=int(args.lbfgs_eval),
        max_eval=int(args.lbfgs_eval),
        history_size=int(args.lbfgs_hist),
    )
    t1 = time.time()
    raw, fit_iter = model.fit_vecc_lbfgs(params, opt, max_steps=int(args.lbfgs_steps), grad_tol=float(args.grad_tol))
    fit_s = time.time() - t1

    est = backmap(raw)
    metrics = calculate_metrics(est, truth)
    loss = float(raw[-1])
    fit_steps = int(fit_iter) + 1
    diag: dict[str, Any] = {}
    if hasattr(model, "cluster_summary"):
        diag.update(model.cluster_summary())

    n_cond_points_nominal = int(diag.get("max_cond_points", 0))

    row = {
        "model_family": spec["model_family"],
        "spec_name": spec["spec_name"],
        "smooth": smooth,
        "mean_design": args.mean_design,
        "cluster_block_shape": f"{args.cluster_block_shape[0]}x{args.cluster_block_shape[1]}",
        "cluster_neighbor_blocks": spec.get("cluster_neighbor_blocks", ""),
        "n_cond_points_nominal": n_cond_points_nominal,
        "loss": loss,
        "converged": int(np.isfinite(loss) and fit_steps < int(args.lbfgs_steps)),
        "fit_steps": fit_steps,
        "precompute_s": pre_s,
        "fit_s": fit_s,
        "total_s": pre_s + fit_s,
        **diag,
        **metrics,
        **{f"est_{p}": est[p] for p in PARAMS},
        "error": "",
    }
    del model, params, opt
    return row


def make_specs(args: argparse.Namespace) -> list[dict[str, Any]]:
    specs = []
    for b in args.cluster_neighbor_blocks:
        specs.append({"model_family": "cluster", "spec_name": f"cluster_4x4_B{b}", "cluster_neighbor_blocks": int(b)})
    return specs


def choose_asset(asset_bank: list[dict[str, Any]], sim_id: int, args: argparse.Namespace) -> dict[str, Any]:
    if args.asset_sampling == "random":
        rng = np.random.default_rng(args.seed + 10_000 + sim_id)
        return asset_bank[int(rng.integers(0, len(asset_bank)))]
    return asset_bank[(sim_id - 1) % len(asset_bank)]


def round_df(df: pd.DataFrame, digits: int = ROUND_DECIMALS) -> pd.DataFrame:
    out = df.copy()
    cols = out.select_dtypes(include=[np.number]).columns
    out[cols] = out[cols].round(digits)
    return out


def save_csv_rounded(df: pd.DataFrame, path: Path) -> None:
    round_df(df).to_csv(path, index=False, float_format=f"%.{ROUND_DECIMALS}f")


def append_row_csv(path: Path, row: dict[str, Any], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        if not exists:
            writer.writeheader()
        writer.writerow({col: row.get(col, "") for col in columns})


def existing_completed(raw_csv: Path) -> set[tuple[int, str]]:
    if not raw_csv.exists():
        return set()
    df = pd.read_csv(raw_csv)
    if df.empty:
        return set()
    ok = df[df["error"].fillna("") == ""] if "error" in df.columns else df
    return {
        (int(r.sim_id), str(r.spec_name))
        for r in ok.itertuples(index=False)
        if pd.notna(r.sim_id) and pd.notna(r.spec_name)
    }


def make_model_summary(df: pd.DataFrame) -> pd.DataFrame:
    ok = df[df["error"].fillna("") == ""].copy() if "error" in df.columns else df.copy()
    if ok.empty:
        return pd.DataFrame()
    rows = []
    metric_cols = [
        "loss",
        "overall_rmsre",
        "median_abs_error",
        "precompute_s",
        "fit_s",
        "total_s",
        "n_cond_points_nominal",
        "n_batches",
        "n_target_points",
    ]
    for keys, sub in ok.groupby(["model_family", "spec_name"], dropna=False):
        row = {"model_family": keys[0], "spec_name": keys[1], "n": int(len(sub))}
        for col in metric_cols:
            vals = pd.to_numeric(sub[col], errors="coerce").dropna().to_numpy(dtype=float) if col in sub else np.asarray([])
            if len(vals) == 0:
                continue
            p10, p90 = np.percentile(vals, [10, 90])
            row[f"{col}_median"] = float(np.median(vals))
            row[f"{col}_p90_p10"] = float(p90 - p10)
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["overall_rmsre_median", "median_abs_error_median"])


def make_param_summary(df: pd.DataFrame, truth: dict[str, float]) -> pd.DataFrame:
    ok = df[df["error"].fillna("") == ""].copy() if "error" in df.columns else df.copy()
    if ok.empty:
        return pd.DataFrame()
    rows = []
    for keys, sub in ok.groupby(["model_family", "spec_name"], dropna=False):
        for p in PARAMS:
            vals = pd.to_numeric(sub.get(f"est_{p}"), errors="coerce").dropna().to_numpy(dtype=float)
            if len(vals) == 0:
                continue
            tv = truth[p]
            abs_vals = np.abs(vals - tv)
            denom = abs(tv) if abs(tv) >= 0.01 else 1.0
            re_vals = abs_vals / denom
            p10_abs, p90_abs = np.percentile(abs_vals, [10, 90])
            rows.append(
                {
                    "model_family": keys[0],
                    "spec_name": keys[1],
                    "parameter": p,
                    "true": tv,
                    "n": int(len(vals)),
                    "rmsre": float(np.sqrt(np.mean(re_vals**2))),
                    "median_abs_error": float(np.median(abs_vals)),
                    "p90_p10_abs_error": float(p90_abs - p10_abs),
                    "median_re": float(np.median(re_vals)),
                    "estimate_median": float(np.median(vals)),
                    "estimate_mean": float(np.mean(vals)),
                }
            )
    return pd.DataFrame(rows).sort_values(["parameter", "rmsre", "median_abs_error"])


def refresh_outputs(raw_csv: Path, model_csv: Path, param_csv: Path, error_csv: Path, txt_path: Path, truth: dict[str, float]) -> None:
    if not raw_csv.exists():
        return
    df = pd.read_csv(raw_csv)
    model_summary = make_model_summary(df)
    param_summary = make_param_summary(df, truth)
    err = df[df["error"].fillna("") != ""].copy() if "error" in df.columns else pd.DataFrame()
    if not model_summary.empty:
        save_csv_rounded(model_summary, model_csv)
    if not param_summary.empty:
        save_csv_rounded(param_summary, param_csv)
    if not err.empty:
        err.to_csv(error_csv, index=False)

    ok_n = int((df["error"].fillna("") == "").sum()) if "error" in df else int(len(df))
    err_n = int((df["error"].fillna("") != "").sum()) if "error" in df else 0
    lines = [
        f"Updated: {datetime.now().isoformat(timespec='seconds')}",
        f"Rows: {len(df)} completed: {ok_n} errors: {err_n}",
        "",
        "Top pure-space Vecchia comparison summary:",
    ]
    if not model_summary.empty:
        cols = [
            "model_family",
            "spec_name",
            "n",
            "overall_rmsre_median",
            "overall_rmsre_p90_p10",
            "median_abs_error_median",
            "total_s_median",
            "n_cond_points_nominal_median",
        ]
        cols = [c for c in cols if c in model_summary.columns]
        lines.append(round_df(model_summary[cols].head(20)).to_string(index=False))
    if not param_summary.empty:
        lines.extend(["", "Parameter summary preview:"])
        cols = ["model_family", "spec_name", "parameter", "n", "rmsre", "median_abs_error", "p90_p10_abs_error", "median_re"]
        lines.append(round_df(param_summary[cols].head(35)).to_string(index=False))
    if not err.empty:
        lines.extend(["", "Recent errors:"])
        lines.append(err.tail(20).to_string(index=False))
    txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines[:4]), flush=True)
    if not model_summary.empty:
        print(round_df(model_summary.head(15)).to_string(index=False), flush=True)


def add_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--num-sims", type=int, default=200)
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--years", type=str, default="2022,2023,2024,2025")
    parser.add_argument("--day-idxs", type=str, default="all")
    parser.add_argument("--max-asset-days", type=int, default=0)
    parser.add_argument("--asset-sampling", type=str, default="cycle", choices=["cycle", "random"])
    parser.add_argument("--sim-data-root", type=Path, default=Path("/home/jl2815/tco/exercise_output/sim_data/july_st_circulant_realpattern"))
    parser.add_argument("--data-kind", type=str, default="real_locations", choices=["gridded", "real_locations"])
    parser.add_argument("--lat-range", type=parse_range, default=parse_range("-3,7"))
    parser.add_argument("--lon-range", type=parse_range, default=parse_range("111,131"))
    parser.add_argument("--cluster-neighbor-blocks", type=parse_int_list, default=parse_int_list("2"))
    parser.add_argument("--cluster-block-shape", type=parse_block_shape, default=parse_block_shape("4x4"))
    parser.add_argument("--mean-design", default="latlon", choices=["lat", "base", "latlon", "hour_spatial"])
    parser.add_argument("--smooth-fallback", type=float, default=0.5)
    parser.add_argument("--cluster-target-chunk-size", type=int, default=96)
    parser.add_argument("--min-target-points", type=int, default=1)
    parser.add_argument("--lbfgs-steps", type=int, default=5)
    parser.add_argument("--lbfgs-eval", type=int, default=15)
    parser.add_argument("--lbfgs-hist", type=int, default=10)
    parser.add_argument("--grad-tol", type=float, default=1e-5)
    parser.add_argument("--init-noise", type=float, default=0.25)
    parser.add_argument("--summary-every", type=int, default=5)
    parser.add_argument("--no-center-response", dest="center_response", action="store_false")
    parser.set_defaults(center_response=True)
    parser.add_argument("--require-cuda", action="store_true")
    parser.add_argument("--resume", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--out-dir", type=Path, default=Path("/home/jl2815/tco/exercise_output/estimates/day/pure_space_cluster_b2_111131_052426"))


def main() -> None:
    parser = argparse.ArgumentParser()
    add_args(parser)
    args = parser.parse_args()

    if args.require_cuda and DEVICE.type != "cuda":
        raise RuntimeError("--require-cuda was passed, but torch.cuda.is_available() is False")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    raw_csv = args.out_dir / "all_fits_summary.csv"
    model_csv = args.out_dir / "running_model_summary.csv"
    param_csv = args.out_dir / "running_param_summary.csv"
    error_csv = args.out_dir / "running_errors.csv"
    txt_path = args.out_dir / "running_summary.txt"
    truth_json = args.out_dir / "truth_params_iso_reference.json"
    config_json = args.out_dir / "run_config.json"

    set_seed(args.seed)
    print("SRC:", SRC, flush=True)
    print("DEVICE:", DEVICE, flush=True)
    print("torch:", torch.__version__, flush=True)
    print("args:", vars(args), flush=True)
    print("NOTE: loading pre-generated simulation assets; no new simulation is run.", flush=True)

    asset_bank, truth = build_asset_bank(args)
    specs = make_specs(args)
    truth_json.write_text(json.dumps(truth, indent=2), encoding="utf-8")
    config_json.write_text(
        json.dumps(
            {
                **{k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items()},
                "src": SRC,
                "device": str(DEVICE),
                "n_assets_loaded": len(asset_bank),
                "n_specs": len(specs),
                "specs": specs,
                "truth_range_convention": "range=sqrt(range_lat*range_lon)",
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    done = existing_completed(raw_csv) if args.resume else set()
    fit_id = 0
    if raw_csv.exists():
        old = pd.read_csv(raw_csv)
        if not old.empty and "fit_id" in old:
            old_fit_ids = pd.to_numeric(old["fit_id"], errors="coerce").dropna()
            if not old_fit_ids.empty:
                fit_id = int(old_fit_ids.max())

    print("truth iso reference:", {k: truth[k] for k in PARAMS}, flush=True)
    print(f"Loaded {len(asset_bank)} day assets; specs={len(specs)}", flush=True)

    for sim_id in range(1, int(args.num_sims) + 1):
        print("\n" + "=" * 100, flush=True)
        print(f"Simulation/day draw {sim_id}/{args.num_sims}", flush=True)
        asset = choose_asset(asset_bank, sim_id, args)
        iter_seed = int(args.seed + sim_id)
        set_seed(iter_seed)
        rng = np.random.default_rng(iter_seed)

        source_map_raw = {
            k: v.to(device=DEVICE, dtype=DTYPE, non_blocking=True).contiguous()
            for k, v in asset["source_map"].items()
        }
        grid_coords_np = np.asarray(asset["grid_coords_np"], dtype=np.float64)
        n_valid = sum(int(torch.isfinite(v[:, 2]).sum().item()) for v in source_map_raw.values())
        print(
            f"asset=year{asset['year']} day_idx={asset['day_idx']} n_grid={asset['n_grid']:,} "
            f"n_valid={n_valid:,} valid={asset['valid_by_t']}",
            flush=True,
        )

        for spec in specs:
            key = (sim_id, spec["spec_name"])
            if args.resume and key in done:
                print(f"Skipping completed sim={sim_id} spec={spec['spec_name']}", flush=True)
                continue

            fit_id += 1
            print(f"\n--- fit_id={fit_id} {spec['spec_name']} ---", flush=True)
            row_base = {
                "fit_id": fit_id,
                "sim_id": sim_id,
                "seed": iter_seed,
                "asset_year": asset["year"],
                "asset_day_idx": asset["day_idx"],
                "asset_first_key": asset["day_keys"][0],
                "data_kind": args.data_kind,
                "n_valid": int(n_valid),
                "n_grid": int(asset["n_grid"]),
                "valid_by_t": json.dumps(asset["valid_by_t"], separators=(",", ":")),
            }
            try:
                row = fit_model(spec, source_map_raw, grid_coords_np, truth, args, rng)
                row.update(row_base)
                compact = {
                    k: (round(v, 5) if isinstance(v, (float, np.floating)) else v)
                    for k, v in row.items()
                    if k in ["spec_name", "loss", "overall_rmsre", "median_abs_error", "total_s", "n_cond_points_nominal"]
                }
                print("RESULT:", compact, flush=True)
            except Exception as exc:
                row = {
                    **row_base,
                    "model_family": spec["model_family"],
                    "spec_name": spec["spec_name"],
                    "smooth": truth.get("smooth", args.smooth_fallback),
                    "mean_design": args.mean_design,
                    "cluster_block_shape": f"{args.cluster_block_shape[0]}x{args.cluster_block_shape[1]}",
                    "cluster_neighbor_blocks": spec.get("cluster_neighbor_blocks", ""),
                    "error": repr(exc),
                }
                print("ERROR:", repr(exc), flush=True)

            append_row_csv(raw_csv, row, ROW_COLUMNS)
            if fit_id % int(args.summary_every) == 0:
                refresh_outputs(raw_csv, model_csv, param_csv, error_csv, txt_path, truth)
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        refresh_outputs(raw_csv, model_csv, param_csv, error_csv, txt_path, truth)

    refresh_outputs(raw_csv, model_csv, param_csv, error_csv, txt_path, truth)
    print("Done.", flush=True)


if __name__ == "__main__":
    main()
