#!/usr/bin/env python3
"""Vecchia conditional eigen diagnostics for July ST smooth=0.3 simulations.

This script compares two nugget-zero ST corridor Vecchia models on the simulated
July gridded data generated by
``generate_july_st_circulant_real_locations_2022_2025_smooth0p3_nugget0_060626.py``:

  - Matérn smooth=0.3, the data-generating smoothness family;
  - generalized Cauchy alpha=0.75, beta=0.5.

The diagnostic is not a dense full-covariance eigendecomposition.  Instead, it
uses the already fitted Vecchia factorization.  For each 4x4 target block at
each of the 8 daily time slots, it forms the conditional covariance

    S = Cov(Y_target | Y_conditioning)

from the block Cholesky factor, eigendecomposes this small conditional block,
projects out the fitted mean-design column space in the resulting conditional
eigen-coordinate system, and records squared projected residual scores.  All
target-block scores for the day are pooled and sorted by conditional eigenvalue,
yielding a scalable full-domain daily curve.

The projection keeps the original conditional-eigenvalue ordering and uses
leverage-adjusted expected increments 1 - h_j.  Therefore the plotted reference
bands are diagnostic reference bands, not exact independent chi-square bands:
after projection, coordinate residuals have correct marginal variances but are
correlated.
"""

from __future__ import annotations

import argparse
import contextlib
import gc
import io
import json
import math
import os
import re
import sys
import time
import traceback
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

os.environ.setdefault("MPLCONFIGDIR", str(Path(os.environ.get("TMPDIR", "/tmp")) / "matplotlib"))
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch.nn import Parameter


HERE = Path(__file__).resolve().parent
SPACE_TIME_DIR = HERE.parent
for path in [HERE, SPACE_TIME_DIR]:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

AMAREL_SRC = Path("/home/jl2815/tco")
LOCAL_SRC = Path("/Users/joonwonlee/Documents/GEMS_TCO-1/src")
SRC = AMAREL_SRC if AMAREL_SRC.exists() else LOCAL_SRC
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from GEMS_TCO.vecchia_realdata_corridor_width_4x4_lag643 import (  # noqa: E402
    BLOCK_SHAPE,
    LAG_COUNTS,
    REFERENCE_ADVEC_LON_ABS,
    SPEC_NAME as VECCHIA_SPEC_NAME,
)
from GEMS_TCO.vecchia_st_generalized_cauchy import (  # noqa: E402
    RealDataCorridorWidth4x4Lag643NoNuggetGeneralizedCauchyFit,
)
from GEMS_TCO.vecchia_st_spline import (  # noqa: E402
    RealDataCorridorWidth4x4Lag643NoNuggetSplineFit,
)


DTYPE = torch.double
ROUND_DECIMALS = 6
LOSS_DECIMALS = 5
BROWN_BRIDGE_Q95 = 1.3581015157406195
EPS = 1e-12
RUN_STEM = "sim_july_st_s03_n0_vecchia_conditional_eig_matern_gc075b05_061826"

MODEL_SPECS: dict[str, dict[str, Any]] = {
    "matern_s03": {
        "family": "matern",
        "smooth": 0.3,
        "gc_alpha": np.nan,
        "gc_beta": np.nan,
        "label": "Matern s=0.3 nugget0",
        "color": "#1f77b4",
    },
    "gc_a075_b05": {
        "family": "cauchy",
        "smooth": np.nan,
        "gc_alpha": 0.75,
        "gc_beta": 0.5,
        "label": "GC a=0.75 b=0.5 nugget0",
        "color": "#d62728",
    },
}

TRUE_INIT_PHYSICAL = {
    "sigmasq": 10.0,
    "range_lat": 0.2,
    "range_lon": 0.3,
    "range_time": 2.0,
    "advec_lat": 0.08,
    "advec_lon": -0.2,
    "nugget": 0.0,
}


@dataclass
class DayAsset:
    year: int
    month: int
    day_idx: int
    day_label: str
    keys: list[str]
    source_map: dict[str, torch.Tensor]
    grid_coords_np: np.ndarray
    monthly_mean: float
    n_rows_per_time: int
    n_valid: int
    n_total: int


def default_data_root() -> Path:
    amarel = Path("/home/jl2815/tco/exercise_output/sim_data/july_st_circulant_realpattern_smooth0p3_nugget0")
    if amarel.exists():
        return amarel
    local = Path("/Users/joonwonlee/Documents/GEMS_DATA/simulation/july_st_circulant_realpattern_smooth0p3_nugget0")
    if local.exists():
        return local
    return Path("/Users/joonwonlee/Documents/GEMS_TCO-1/outputs/sim_data/july_st_circulant_realpattern_smooth0p3_nugget0")


def default_output_root() -> Path:
    if Path("/home/jl2815").exists():
        return Path(f"/home/jl2815/tco/exercise_output/summer/{RUN_STEM}")
    return Path(f"/Users/joonwonlee/Documents/GEMS_TCO-1/outputs/summer_26/{RUN_STEM}")


def clean_json_value(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (np.floating, np.integer)):
        return value.item()
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, torch.Tensor):
        if value.numel() == 1:
            return float(value.detach().cpu().item())
        return value.detach().cpu().tolist()
    if isinstance(value, (list, tuple)):
        return [clean_json_value(v) for v in value]
    if isinstance(value, dict):
        return {str(k): clean_json_value(v) for k, v in value.items()}
    return value


def parse_tokens(values: Iterable[str]) -> list[str]:
    out: list[str] = []
    for value in values:
        out.extend(part.strip() for part in str(value).split(",") if part.strip())
    return out


def parse_int_tokens(values: Iterable[str]) -> list[int]:
    return [int(v) for v in parse_tokens(values)]


def parse_day_idxs(text: str, n_keys: int | None = None, hours_per_day: int = 8) -> list[int]:
    text = str(text).strip().lower()
    if text == "all":
        if n_keys is None:
            raise ValueError("--days all requires n_keys")
        return list(range(int(n_keys) // int(hours_per_day)))
    parts = [p.strip() for p in text.split(",") if p.strip()]
    if len(parts) == 2:
        start, end = int(parts[0]), int(parts[1])
        return list(range(start, end))
    return [int(p) for p in parts]


def parse_pair(text: str, cast=float) -> list[Any]:
    parts = [p.strip() for p in str(text).split(",") if p.strip()]
    if len(parts) != 2:
        raise argparse.ArgumentTypeError(f"Expected two comma-separated values, got {text!r}")
    return [cast(parts[0]), cast(parts[1])]


def parse_gems_hour_key(key: str) -> pd.Timestamp | None:
    pat = r"^y(?P<yy>\d{2})m(?P<mm>\d{2})day(?P<dd>\d{2})_hm(?P<hh>\d{2}):(?P<minute>\d{2})$"
    match = re.match(pat, str(key))
    if not match:
        return None
    parts = {name: int(value) for name, value in match.groupdict().items()}
    return pd.Timestamp(
        year=2000 + parts["yy"],
        month=parts["mm"],
        day=parts["dd"],
        hour=parts["hh"],
        minute=parts["minute"],
        tz="UTC",
    )


def sorted_hour_keys(obj: dict[str, pd.DataFrame]) -> list[str]:
    parsed = []
    fallback = []
    for key in obj:
        ts = parse_gems_hour_key(str(key))
        if ts is None:
            fallback.append(str(key))
        else:
            parsed.append((ts, str(key)))
    if parsed:
        return [key for _, key in sorted(parsed)]
    return sorted(fallback)


def simulated_pickle_path(data_root: Path, year: int, kind: str) -> Path:
    name = f"sim_july{int(year)}_st_circulant_{kind}.pkl"
    return Path(data_root) / f"{int(year)}_july_st_circulant" / name


def resolve_device(args: argparse.Namespace) -> torch.device:
    if args.device is not None:
        device = torch.device(args.device)
        if device.type == "cuda" and not torch.cuda.is_available():
            raise RuntimeError(f"Requested {device}, but CUDA is not available.")
        return device
    if torch.cuda.is_available():
        return torch.device("cuda")
    if args.cuda_fallback == "error" or args.require_cuda:
        raise RuntimeError("CUDA is not available and CUDA fallback is disabled.")
    return torch.device("cpu")


def count_valid(source_map: dict[str, torch.Tensor]) -> tuple[int, int, dict[str, int]]:
    n_valid = 0
    n_total = 0
    valid_by_t: dict[str, int] = {}
    for key, tensor in source_map.items():
        valid = (~torch.isnan(tensor[:, 2])) & (~torch.isnan(tensor[:, 0])) & (~torch.isnan(tensor[:, 1]))
        count = int(valid.sum().item())
        n_valid += count
        n_total += int(tensor.shape[0])
        valid_by_t[str(key)] = count
    return n_valid, n_total, valid_by_t


def assert_grid_order_consistent(df_map: dict[str, pd.DataFrame], keys: list[str], base_coords: np.ndarray) -> None:
    for key in keys:
        coords = df_map[key][["Latitude", "Longitude"]].to_numpy(dtype=np.float64)
        if coords.shape != base_coords.shape or not np.allclose(coords, base_coords, equal_nan=True):
            raise RuntimeError(f"Regular grid coordinate order differs at {key}.")


def build_hour_tensor(
    df: pd.DataFrame,
    t_idx: int,
    monthly_mean: float,
    keep_exact_loc: bool,
    dtype: torch.dtype,
) -> torch.Tensor:
    tmp = df.copy()
    value = pd.to_numeric(tmp["ColumnAmountO3"], errors="coerce").to_numpy(dtype=np.float64)
    centered = value - float(monthly_mean)

    if keep_exact_loc and {"Source_Latitude", "Source_Longitude"}.issubset(tmp.columns):
        lat = pd.to_numeric(tmp["Source_Latitude"], errors="coerce").to_numpy(dtype=np.float64)
        lon = pd.to_numeric(tmp["Source_Longitude"], errors="coerce").to_numpy(dtype=np.float64)
        grid_lat = pd.to_numeric(tmp["Latitude"], errors="coerce").to_numpy(dtype=np.float64)
        grid_lon = pd.to_numeric(tmp["Longitude"], errors="coerce").to_numpy(dtype=np.float64)
        lat = np.where(np.isfinite(lat), lat, grid_lat)
        lon = np.where(np.isfinite(lon), lon, grid_lon)
    else:
        lat = pd.to_numeric(tmp["Latitude"], errors="coerce").to_numpy(dtype=np.float64)
        lon = pd.to_numeric(tmp["Longitude"], errors="coerce").to_numpy(dtype=np.float64)

    base = np.zeros((len(tmp), 4), dtype=np.float64)
    base[:, 0] = lat
    base[:, 1] = lon
    base[:, 2] = centered
    base[:, 3] = float(t_idx)
    base_tensor = torch.from_numpy(base).to(dtype=dtype)
    dummies = F.one_hot(torch.tensor([int(t_idx)], dtype=torch.long), num_classes=8).repeat(len(base_tensor), 1)
    dummies = dummies[:, 1:].to(dtype=dtype)
    return torch.cat([base_tensor, dummies], dim=1).contiguous()


def load_day_assets(args: argparse.Namespace) -> list[DayAsset]:
    data_root = args.data_root or default_data_root()
    years = parse_int_tokens(args.years)
    month = int(args.month)
    lat_range = parse_pair(args.lat_range, float)
    lon_range = parse_pair(args.lon_range, float)
    assets: list[DayAsset] = []

    for year in years:
        path = simulated_pickle_path(data_root, int(year), str(args.sim_kind))
        if not path.exists():
            raise FileNotFoundError(
                f"Simulated {args.sim_kind} pickle not found: {path}. "
                "For this ST Vecchia diagnostic, use the gridded pickle unless you have equal-length real-location maps."
            )
        obj = pd.read_pickle(path)
        if not isinstance(obj, dict):
            raise TypeError(f"Expected dict pickle at {path}, got {type(obj)}")
        key_idx = sorted_hour_keys(obj)
        day_idxs = parse_day_idxs(args.days, n_keys=len(key_idx), hours_per_day=int(args.hours_per_day))

        df_map: dict[str, pd.DataFrame] = {}
        for key in key_idx:
            df = obj[key].copy()
            mask = (
                (pd.to_numeric(df["Latitude"], errors="coerce") >= lat_range[0])
                & (pd.to_numeric(df["Latitude"], errors="coerce") <= lat_range[1])
                & (pd.to_numeric(df["Longitude"], errors="coerce") >= lon_range[0])
                & (pd.to_numeric(df["Longitude"], errors="coerce") <= lon_range[1])
            )
            df_map[key] = df[mask].reset_index(drop=True)

        ozone_vals = [
            pd.to_numeric(df["ColumnAmountO3"], errors="coerce").to_numpy(dtype=np.float64)
            for df in df_map.values()
        ]
        monthly_mean = float(np.nanmean(np.concatenate(ozone_vals))) if ozone_vals else 0.0
        base_coords = df_map[key_idx[0]][["Latitude", "Longitude"]].to_numpy(dtype=np.float64)
        print(
            f"\nLoaded {path}: year={year}, keys={len(key_idx)}, grid={base_coords.shape}, "
            f"monthly_mean={monthly_mean:.6f}",
            flush=True,
        )

        for day_idx in day_idxs:
            start, end = int(day_idx) * int(args.hours_per_day), (int(day_idx) + 1) * int(args.hours_per_day)
            selected_keys = key_idx[start:end]
            if len(selected_keys) != int(args.hours_per_day):
                print(f"Skipping year={year} day_idx={day_idx}: expected {args.hours_per_day} keys, got {len(selected_keys)}", flush=True)
                continue
            assert_grid_order_consistent(df_map, selected_keys, base_coords)
            source_map = {
                key: build_hour_tensor(
                    df_map[key],
                    t_idx=i,
                    monthly_mean=monthly_mean,
                    keep_exact_loc=bool(args.keep_exact_loc),
                    dtype=DTYPE,
                )
                for i, key in enumerate(selected_keys)
            }
            n_valid, n_total, _ = count_valid(source_map)
            ts = parse_gems_hour_key(selected_keys[0])
            day_label = ts.strftime("%Y-%m-%d") if ts is not None else f"{year}-{month:02d}-day{int(day_idx) + 1:02d}"
            assets.append(
                DayAsset(
                    year=int(year),
                    month=month,
                    day_idx=int(day_idx),
                    day_label=day_label,
                    keys=list(selected_keys),
                    source_map={k: v.contiguous() for k, v in source_map.items()},
                    grid_coords_np=base_coords.copy(),
                    monthly_mean=monthly_mean,
                    n_rows_per_time=int(base_coords.shape[0]),
                    n_valid=int(n_valid),
                    n_total=int(n_total),
                )
            )
    return assets


def physical_to_log_phi(params: dict[str, float]) -> list[float]:
    sigmasq = float(params["sigmasq"])
    range_lat = float(params["range_lat"])
    range_lon = float(params["range_lon"])
    range_time = float(params["range_time"])
    phi2 = 1.0 / range_lon
    phi1 = sigmasq * phi2
    phi3 = (range_lon / range_lat) ** 2
    phi4 = (range_lon / range_time) ** 2
    return [
        float(np.log(phi1)),
        float(np.log(phi2)),
        float(np.log(phi3)),
        float(np.log(phi4)),
        float(params["advec_lat"]),
        float(params["advec_lon"]),
    ]


def make_params_list(init_physical: dict[str, float], dtype: torch.dtype, device: torch.device) -> list[Parameter]:
    return [
        Parameter(torch.tensor(val, dtype=dtype, device=device))
        for val in physical_to_log_phi(init_physical)
    ]


def backmap_params(raw: list[float]) -> dict[str, float]:
    vals = [float(x) for x in raw]
    phi1, phi2, phi3, phi4 = np.exp(vals[0]), np.exp(vals[1]), np.exp(vals[2]), np.exp(vals[3])
    range_lon = 1.0 / phi2
    return {
        "sigmasq": float(phi1 / phi2),
        "range_lat": float(range_lon / np.sqrt(phi3)),
        "range_lon": float(range_lon),
        "range_time": float(range_lon / np.sqrt(phi4)),
        "advec_lat": float(vals[4]),
        "advec_lon": float(vals[5]),
        "nugget": 0.0,
    }


def build_model(spec: dict[str, Any], source_map: dict[str, torch.Tensor], grid_coords_np: np.ndarray, args: argparse.Namespace):
    if spec["family"] == "matern":
        return RealDataCorridorWidth4x4Lag643NoNuggetSplineFit(
            smooth=float(spec["smooth"]),
            input_map=source_map,
            grid_coords=grid_coords_np,
            lag1_lon_offset=float(args.real_reference_advec_lon_abs),
            daily_stride=int(args.daily_stride),
            target_chunk_size=int(args.target_chunk_size),
            min_target_points=int(args.min_target_points),
            spline_n_points=int(args.spline_n_points),
            spline_r_max=float(args.spline_r_max),
        )
    if spec["family"] == "cauchy":
        return RealDataCorridorWidth4x4Lag643NoNuggetGeneralizedCauchyFit(
            gc_alpha=float(spec["gc_alpha"]),
            gc_beta=float(spec["gc_beta"]),
            input_map=source_map,
            grid_coords=grid_coords_np,
            lag1_lon_offset=float(args.real_reference_advec_lon_abs),
            daily_stride=int(args.daily_stride),
            target_chunk_size=int(args.target_chunk_size),
            min_target_points=int(args.min_target_points),
        )
    raise ValueError(f"Unknown model family {spec['family']!r}")


def fit_one_model(asset: DayAsset, model_variant: str, device: torch.device, args: argparse.Namespace) -> tuple[dict[str, Any], Any, torch.Tensor]:
    spec = MODEL_SPECS[model_variant]
    source_map = {
        k: v.to(device=device, dtype=DTYPE, non_blocking=True).contiguous()
        for k, v in asset.source_map.items()
    }
    model = build_model(spec, source_map, asset.grid_coords_np, args)
    params_list = make_params_list(TRUE_INIT_PHYSICAL, dtype=DTYPE, device=device)

    t0 = time.time()
    model.precompute_conditioning_sets()
    precompute_s = time.time() - t0

    optimizer = model.set_optimizer(
        params_list,
        lr=float(args.lbfgs_lr),
        max_iter=int(args.lbfgs_eval),
        max_eval=int(args.lbfgs_eval),
        history_size=int(args.lbfgs_history),
    )

    t1 = time.time()
    if args.suppress_fit_prints:
        with contextlib.redirect_stdout(io.StringIO()):
            out, steps_ran = model.fit_vecc_lbfgs(
                params_list,
                optimizer,
                max_steps=int(args.lbfgs_steps),
                grad_tol=float(args.grad_tol),
            )
    else:
        out, steps_ran = model.fit_vecc_lbfgs(
            params_list,
            optimizer,
            max_steps=int(args.lbfgs_steps),
            grad_tol=float(args.grad_tol),
        )
    fit_s = time.time() - t1

    raw_params = [float(x) for x in out[:6]]
    params_tensor = torch.stack([p.detach().reshape(()) for p in params_list]).to(device=device, dtype=DTYPE)
    beta = model.get_gls_beta(params_tensor).detach()
    est = backmap_params(raw_params)
    cluster_summary = model.cluster_summary()
    fit_loss_per_obs = float(out[-1])
    row = {
        "status": "ok",
        "error": "",
        "year": int(asset.year),
        "month": int(asset.month),
        "day_idx": int(asset.day_idx),
        "day": str(asset.day_label),
        "model_variant": str(model_variant),
        "model_family": str(spec["family"]),
        "model_label": str(spec["label"]),
        "smooth": float(spec["smooth"]) if pd.notna(spec["smooth"]) else np.nan,
        "gc_alpha": float(spec["gc_alpha"]) if pd.notna(spec["gc_alpha"]) else np.nan,
        "gc_beta": float(spec["gc_beta"]) if pd.notna(spec["gc_beta"]) else np.nan,
        "nugget_mode": "zero",
        "n_rows_per_time": int(asset.n_rows_per_time),
        "n_valid_o3": int(asset.n_valid),
        "n_total_rows": int(asset.n_total),
        "valid_rate": float(asset.n_valid / asset.n_total) if asset.n_total else np.nan,
        "monthly_mean": float(asset.monthly_mean),
        "first_key": asset.keys[0],
        "last_key": asset.keys[-1],
        "spec_name": VECCHIA_SPEC_NAME,
        "block_shape": f"{BLOCK_SHAPE[0]}x{BLOCK_SHAPE[1]}",
        "lag_pattern": f"{LAG_COUNTS[0]}/{LAG_COUNTS[1]}/{LAG_COUNTS[2]}",
        "reference_advec_lon_abs": float(args.real_reference_advec_lon_abs),
        "vecchia_loss_per_obs": fit_loss_per_obs,
        "steps_raw": int(steps_ran),
        "precompute_s": float(precompute_s),
        "fit_s": float(fit_s),
        "total_fit_s": float(precompute_s + fit_s),
        **{f"est_{k}": float(est[k]) for k in ["sigmasq", "range_lat", "range_lon", "range_time", "advec_lat", "advec_lon", "nugget"]},
        **cluster_summary,
    }
    return row, model, beta


def conditional_eigen_curve(
    model: Any,
    params: torch.Tensor,
    beta: torch.Tensor,
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    if not getattr(model, "is_precomputed", False):
        raise RuntimeError("Model must be precomputed before conditional_eigen_curve.")
    if not hasattr(model, "_cluster_batches"):
        raise RuntimeError("This diagnostic currently expects a cluster Vecchia model with _cluster_batches.")

    eigen_chunks: list[torch.Tensor] = []
    y_score_chunks: list[torch.Tensor] = []
    x_score_chunks: list[torch.Tensor] = []
    local_rank_chunks: list[torch.Tensor] = []
    log_det_half_total = params.new_tensor(0.0)
    n_blocks = 0
    n_scores = 0
    diag_chunk_size = int(args.diag_chunk_size) if int(args.diag_chunk_size) > 0 else int(args.target_chunk_size)
    diag_chunk_size = max(1, diag_chunk_size)

    with torch.no_grad():
        for batch in model._cluster_batches:
            if batch.X.shape[0] == 0:
                continue
            target_slice = slice(batch.max_cond_points, batch.max_cond_points + batch.target_size)
            target_size = int(batch.target_size)
            for start in range(0, batch.X.shape[0], diag_chunk_size):
                end = min(start + diag_chunk_size, batch.X.shape[0])
                cov = model.matern_cov_batched(params, batch.X[start:end])
                L = torch.linalg.cholesky(cov)
                Z_locs = torch.linalg.solve_triangular(L, batch.Locs[start:end], upper=False)
                Z_y = torch.linalg.solve_triangular(L, batch.Y[start:end], upper=False)
                u_X = Z_locs[:, target_slice, :]
                u_y = Z_y[:, target_slice, 0]

                L_tt = L[:, target_slice, target_slice]
                cond_y = torch.bmm(L_tt, u_y.unsqueeze(-1))
                cond_X = torch.bmm(L_tt, u_X)
                s_cond = torch.bmm(L_tt, L_tt.transpose(1, 2))
                evals, evecs = torch.linalg.eigh(0.5 * (s_cond + s_cond.transpose(1, 2)))
                evals = evals.clamp_min(EPS).flip(dims=[1])
                evecs = evecs.flip(dims=[2])
                sqrt_evals = torch.sqrt(evals).unsqueeze(-1)
                y_scores = torch.bmm(evecs.transpose(1, 2), cond_y).squeeze(-1) / sqrt_evals.squeeze(-1)
                x_scores = torch.bmm(evecs.transpose(1, 2), cond_X) / sqrt_evals

                log_diag = torch.log(torch.diagonal(L_tt, dim1=1, dim2=2))
                log_det_half_total = log_det_half_total + log_diag.sum()
                n_blocks += int(end - start)
                n_scores += int(y_scores.numel())

                eigen_chunks.append(evals.reshape(-1).detach())
                y_score_chunks.append(y_scores.reshape(-1).detach())
                x_score_chunks.append(x_scores.reshape(-1, x_scores.shape[-1]).detach())
                local_rank = torch.arange(1, target_size + 1, device=params.device, dtype=torch.int16).repeat(int(end - start))
                local_rank_chunks.append(local_rank)

                del cov, L, Z_locs, Z_y, u_X, u_y, L_tt, cond_y, cond_X, s_cond, evals, evecs, sqrt_evals, y_scores, x_scores

    if not eigen_chunks:
        raise RuntimeError("No conditional eigen scores were generated.")

    eigenvalues = torch.cat(eigen_chunks).to(dtype=DTYPE)
    y_scores = torch.cat(y_score_chunks).to(dtype=DTYPE)
    x_scores = torch.cat(x_score_chunks).to(dtype=DTYPE)
    local_rank = torch.cat(local_rank_chunks)
    finite = torch.isfinite(eigenvalues) & torch.isfinite(y_scores) & torch.isfinite(x_scores).all(dim=1) & (eigenvalues > 0.0)
    eigenvalues = eigenvalues[finite]
    y_scores = y_scores[finite]
    x_scores = x_scores[finite]
    local_rank = local_rank[finite]

    beta_vec = beta.detach().reshape(-1).to(device=x_scores.device, dtype=DTYPE)
    residual = y_scores - x_scores @ beta_vec
    xtx = x_scores.T @ x_scores
    xtx_jitter = torch.eye(xtx.shape[0], device=xtx.device, dtype=DTYPE) * 1e-6
    xtx_inv = torch.linalg.pinv(xtx + xtx_jitter)
    leverage = torch.einsum("ij,jk,ik->i", x_scores, xtx_inv, x_scores)
    leverage = leverage.clamp(0.0, 1.0 - 1e-10)
    expected_increment = 1.0 - leverage
    y2 = residual.pow(2)

    order = torch.argsort(eigenvalues, descending=True)
    eigenvalues = eigenvalues[order]
    y2 = y2[order]
    local_rank = local_rank[order]
    leverage = leverage[order]
    expected_increment = expected_increment[order]

    index = torch.arange(1, int(y2.numel()) + 1, device=y2.device, dtype=torch.int64)
    csum = torch.cumsum(y2, dim=0)
    expected_csum = torch.cumsum(expected_increment, dim=0)
    m = int(y2.numel())
    residual_df = float(expected_increment.sum().detach().cpu().item())
    width = float(args.brown_bridge_q) * math.sqrt(2.0 * max(residual_df, 1.0))
    bridge_d = (
        float(torch.max(torch.abs(csum - expected_csum)).detach().cpu().item() / math.sqrt(2.0 * max(residual_df, 1.0)))
        if m
        else np.nan
    )
    loss_total = float((log_det_half_total + 0.5 * y2.sum()).detach().cpu().item())

    index_np = index.detach().cpu().numpy()
    eigenvalues_np = eigenvalues.detach().cpu().numpy()
    local_rank_np = local_rank.detach().cpu().numpy().astype(np.int16, copy=False)
    leverage_np = leverage.detach().cpu().numpy()
    expected_increment_np = expected_increment.detach().cpu().numpy()
    y2_np = y2.detach().cpu().numpy()
    csum_np = csum.detach().cpu().numpy()
    expected_csum_np = expected_csum.detach().cpu().numpy()

    curve = pd.DataFrame(
        {
            "index": index_np,
            "frac_index": expected_csum_np / max(residual_df, EPS),
            "conditional_eigenvalue": eigenvalues_np,
            "local_eigen_rank": local_rank_np,
            "leverage": leverage_np,
            "expected_increment": expected_increment_np,
            "y2": y2_np,
            "cumsum_y2": csum_np,
            "scaled_cumsum": csum_np / max(residual_df, EPS),
            "expected": expected_csum_np,
            "scaled_expected": expected_csum_np / max(residual_df, EPS),
            "band_lower": expected_csum_np - width,
            "band_upper": expected_csum_np + width,
            "scaled_band_lower": expected_csum_np / max(residual_df, EPS) - width / max(residual_df, EPS),
            "scaled_band_upper": expected_csum_np / max(residual_df, EPS) + width / max(residual_df, EPS),
        }
    )
    rank_summary = (
        pd.DataFrame({"local_eigen_rank": local_rank_np, "y2": y2_np, "expected_increment": expected_increment_np})
        .groupby("local_eigen_rank", as_index=False)
        .agg(
            local_rank_sum_y2=("y2", "sum"),
            local_rank_expected=("expected_increment", "sum"),
            local_rank_n=("y2", "size"),
        )
    )
    summary = {
        "n_conditional_blocks": int(n_blocks),
        "n_conditional_scores": int(m),
        "n_scores_before_filter": int(n_scores),
        "residual_df": residual_df,
        "mean_leverage": float(leverage.mean().detach().cpu().item()) if m else np.nan,
        "max_leverage": float(leverage.max().detach().cpu().item()) if m else np.nan,
        "conditional_loss_total": float(loss_total),
        "conditional_loss_per_score": float(loss_total / max(m, 1)),
        "mean_y2": float((y2.sum() / max(residual_df, EPS)).detach().cpu().item()) if m else np.nan,
        "sum_y2": float(csum[-1].detach().cpu().item()) if m else np.nan,
        "max_abs_bridge_scaled": bridge_d,
        "min_conditional_eigenvalue": float(eigenvalues.min().detach().cpu().item()) if m else np.nan,
        "max_conditional_eigenvalue": float(eigenvalues.max().detach().cpu().item()) if m else np.nan,
    }
    for _, row in rank_summary.iterrows():
        rank = int(row["local_eigen_rank"])
        summary[f"local_rank{rank:02d}_mean_y2"] = float(row["local_rank_sum_y2"] / max(row["local_rank_expected"], EPS))
        summary[f"local_rank{rank:02d}_n"] = int(row["local_rank_n"])
    return curve, summary


def resample_curve(curve: pd.DataFrame, n_grid: int = 200) -> pd.DataFrame:
    if curve.empty:
        return pd.DataFrame()
    frac = curve["frac_index"].to_numpy(dtype=np.float64)
    scaled = curve["scaled_cumsum"].to_numpy(dtype=np.float64)
    grid = np.linspace(1.0 / int(n_grid), 1.0, int(n_grid))
    vals = np.interp(grid, frac, scaled)
    residual_df = float(curve["expected"].iloc[-1]) if "expected" in curve.columns and not curve.empty else float(len(curve))
    return pd.DataFrame({"frac_index": grid, "scaled_cumsum": vals, "n_scores": int(len(curve)), "residual_df": residual_df})


def model_label(model_variant: str, summary: pd.DataFrame | None = None) -> str:
    spec = MODEL_SPECS.get(model_variant, {})
    label = str(spec.get("label", model_variant))
    if summary is not None and not summary.empty and "vecchia_loss_per_obs" in summary.columns:
        vals = pd.to_numeric(
            summary.loc[summary["model_variant"] == model_variant, "vecchia_loss_per_obs"],
            errors="coerce",
        ).dropna()
        if not vals.empty:
            label += f" loss/obs={float(vals.mean()):.{LOSS_DECIMALS}f}"
    return label


def plot_daily_comparison(curves: dict[str, pd.DataFrame], summary_rows: list[dict[str, Any]], out_path: Path, title: str) -> None:
    if not curves:
        return
    summary = pd.DataFrame(summary_rows)
    fig, ax = plt.subplots(figsize=(6.4, 5.2))
    y_max = 1.05
    for model_variant, curve in curves.items():
        if curve.empty:
            continue
        color = MODEL_SPECS.get(model_variant, {}).get("color", None)
        x = curve["frac_index"].to_numpy(dtype=np.float64)
        y = curve["scaled_cumsum"].to_numpy(dtype=np.float64)
        y_max = max(y_max, float(np.nanmax(y)) * 1.04)
        ax.plot(x, y, color=color, linewidth=1.8, label=model_label(model_variant, summary))
    grid = np.linspace(0.0, 1.0, 200)
    ax.plot(grid, grid, color="0.45", linewidth=1.2)
    first_curve = next(iter(curves.values()))
    if not first_curve.empty:
        m_bar = max(float(first_curve["expected"].iloc[-1]) if "expected" in first_curve.columns else float(len(first_curve)), 1.0)
        band = BROWN_BRIDGE_Q95 * math.sqrt(2.0 / m_bar)
        ax.plot(grid, grid - band, color="0.65", linestyle=(0, (4, 4)), linewidth=0.9)
        ax.plot(grid, grid + band, color="0.65", linestyle=(0, (4, 4)), linewidth=0.9)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, y_max)
    ax.set_xlabel("projected expected df fraction, sorted by conditional eigenvalue")
    ax.set_ylabel("projected cumulative squared score / residual df")
    ax.set_title(title)
    ax.grid(alpha=0.22)
    ax.legend(fontsize=8)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def write_monthly_outputs(avg_rows: list[pd.DataFrame], summary_rows: list[dict[str, Any]], out_dir: Path, year: int) -> None:
    if not avg_rows:
        return
    all_avg = pd.concat(avg_rows, ignore_index=True)
    summary = pd.DataFrame(summary_rows)
    all_avg.round(ROUND_DECIMALS).to_csv(
        out_dir / f"sim_{year}_vecchia_conditional_eig_daily_resampled_curves.csv",
        index=False,
        float_format=f"%.{ROUND_DECIMALS}f",
    )
    keys = ["model_variant", "frac_index"]
    monthly = (
        all_avg.groupby(keys, as_index=False)
        .agg(
            scaled_cumsum_mean=("scaled_cumsum", "mean"),
            scaled_cumsum_sd=("scaled_cumsum", "std"),
            n_days=("scaled_cumsum", "count"),
            n_scores_mean=("n_scores", "mean"),
            residual_df_mean=("residual_df", "mean"),
        )
        .sort_values(keys)
    )
    monthly.round(ROUND_DECIMALS).to_csv(
        out_dir / f"sim_{year}_vecchia_conditional_eig_monthly_average_curves.csv",
        index=False,
        float_format=f"%.{ROUND_DECIMALS}f",
    )

    fig, ax = plt.subplots(figsize=(6.6, 5.3))
    y_max = 1.05
    for model_variant, g in monthly.groupby("model_variant", sort=True):
        color = MODEL_SPECS.get(str(model_variant), {}).get("color", None)
        g = g.sort_values("frac_index")
        x = g["frac_index"].to_numpy(dtype=np.float64)
        y = g["scaled_cumsum_mean"].to_numpy(dtype=np.float64)
        sd = g["scaled_cumsum_sd"].fillna(0.0).to_numpy(dtype=np.float64)
        y_max = max(y_max, float(np.nanmax(y + sd)) * 1.04)
        ax.plot(x, y, color=color, linewidth=2.0, label=model_label(str(model_variant), summary))
        ax.fill_between(x, y - sd, y + sd, color=color, alpha=0.10, linewidth=0)
    grid = np.linspace(0.0, 1.0, 200)
    ax.plot(grid, grid, color="0.45", linewidth=1.2)
    residual_df_mean = pd.to_numeric(monthly["residual_df_mean"], errors="coerce").dropna()
    if not residual_df_mean.empty:
        band = BROWN_BRIDGE_Q95 * math.sqrt(2.0 / max(float(residual_df_mean.mean()), 1.0))
        ax.plot(grid, grid - band, color="0.65", linestyle=(0, (4, 4)), linewidth=0.9)
        ax.plot(grid, grid + band, color="0.65", linestyle=(0, (4, 4)), linewidth=0.9)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, y_max)
    ax.set_xlabel("projected expected df fraction, sorted by conditional eigenvalue")
    ax.set_ylabel("monthly mean projected cumulative squared score / residual df")
    ax.set_title(f"Sim July {year}: monthly average Vecchia conditional eigen diagnostic")
    ax.grid(alpha=0.22)
    ax.legend(fontsize=8)
    fig.tight_layout()
    plot_dir = out_dir / "monthly_average_plots"
    plot_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(plot_dir / f"sim_{year}_monthly_average_vecchia_conditional_eig_comparison.png", dpi=180, bbox_inches="tight")
    plt.close(fig)


def save_summary(summary_rows: list[dict[str, Any]], out_dir: Path) -> pd.DataFrame:
    df = pd.DataFrame(summary_rows)
    if not df.empty:
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        df[numeric_cols] = df[numeric_cols].round(ROUND_DECIMALS)
    df.to_csv(out_dir / f"{RUN_STEM}_summary.csv", index=False, float_format=f"%.{ROUND_DECIMALS}f")
    return df


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="ST Vecchia conditional eigen diagnostic on smooth=0.3 nugget-zero simulations.")
    parser.add_argument("--data-root", type=Path, default=None)
    parser.add_argument("--sim-kind", choices=["gridded", "real_locations"], default="gridded")
    parser.add_argument("--years", nargs="+", default=["2022", "2023", "2024", "2025"])
    parser.add_argument("--month", type=int, default=7)
    parser.add_argument("--days", default="0,30", help="'0,30' means day_idx 0..29; use 'all' for all complete 8-hour days.")
    parser.add_argument("--hours-per-day", type=int, default=8)
    parser.add_argument("--lat-range", default="-3,2")
    parser.add_argument("--lon-range", default="121,131")
    parser.add_argument("--model-variants", nargs="+", default=["matern_s03", "gc_a075_b05"])
    parser.add_argument("--keep-exact-loc", dest="keep_exact_loc", action="store_true", default=True)
    parser.add_argument("--no-keep-exact-loc", dest="keep_exact_loc", action="store_false")
    parser.add_argument("--real-reference-advec-lon-abs", type=float, default=REFERENCE_ADVEC_LON_ABS)
    parser.add_argument("--daily-stride", type=int, default=2)
    parser.add_argument("--target-chunk-size", type=int, default=32)
    parser.add_argument(
        "--diag-chunk-size",
        type=int,
        default=64,
        help="Number of Vecchia target blocks per GPU diagnostic chunk. Lower this if CUDA memory is tight.",
    )
    parser.add_argument("--min-target-points", type=int, default=1)
    parser.add_argument("--spline-n-points", type=int, default=4000)
    parser.add_argument("--spline-r-max", type=float, default=30.0)
    parser.add_argument("--lbfgs-lr", type=float, default=1.0)
    parser.add_argument("--lbfgs-steps", type=int, default=8)
    parser.add_argument("--lbfgs-eval", type=int, default=20)
    parser.add_argument("--lbfgs-history", type=int, default=10)
    parser.add_argument("--grad-tol", type=float, default=1e-5)
    parser.add_argument("--device", default=None)
    parser.add_argument("--cuda-fallback", choices=["cpu", "error"], default="cpu")
    parser.add_argument("--require-cuda", action="store_true")
    parser.add_argument("--brown-bridge-q", type=float, default=BROWN_BRIDGE_Q95)
    parser.add_argument("--resample-grid", type=int, default=200)
    parser.add_argument("--save-daily-curves", action="store_true")
    parser.add_argument("--suppress-fit-prints", action="store_true")
    parser.add_argument("--out-dir", type=Path, default=None)
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    model_variants = parse_tokens(args.model_variants)
    for variant in model_variants:
        if variant not in MODEL_SPECS:
            raise ValueError(f"Unknown model variant {variant!r}. Known: {sorted(MODEL_SPECS)}")
    device = resolve_device(args)
    out_dir = args.out_dir or default_output_root()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_config = {
        "created": datetime.now().isoformat(timespec="seconds"),
        "script": str(Path(__file__).resolve()),
        "src": str(SRC),
        "device": str(device),
        "args": clean_json_value(vars(args)),
        "model_specs": clean_json_value(MODEL_SPECS),
        "true_init_physical": TRUE_INIT_PHYSICAL,
        "diagnostic_definition": (
            "Vecchia conditional target-block covariance eigenbasis; conditional-eigen scores are projected "
            "off the fitted mean-design column space via P=I-Z(Z'Z)^-1Z'; curves are sorted by conditional eigenvalue "
            "and scaled by cumulative projected expected df sum(1-h_j)"
        ),
        "gpu_optimization": "Conditional scores, projection/leverage, sorting, and cumulative sums stay on the torch device until final CSV/plot materialization.",
        "loss_definition": "Vecchia objective per target observation returned by model, matching total conditional NLL divided by conditional score count",
    }
    (out_dir / "run_config.json").write_text(json.dumps(clean_json_value(run_config), indent=2, sort_keys=True), encoding="utf-8")

    print("SRC:", SRC, flush=True)
    print("device:", device, flush=True)
    print("out_dir:", out_dir, flush=True)
    print("model_variants:", model_variants, flush=True)

    assets = load_day_assets(args)
    summary_rows: list[dict[str, Any]] = []
    avg_rows: list[pd.DataFrame] = []

    for asset in assets:
        print("\n" + "=" * 100, flush=True)
        print(
            f"Day year={asset.year} day_idx={asset.day_idx} day={asset.day_label} "
            f"rows/time={asset.n_rows_per_time:,} valid={asset.n_valid:,}/{asset.n_total:,}",
            flush=True,
        )
        print("=" * 100, flush=True)
        day_curves: dict[str, pd.DataFrame] = {}
        day_summary_rows: list[dict[str, Any]] = []

        for model_variant in model_variants:
            print(f"\n--- Fitting and diagnosing {model_variant} ---", flush=True)
            model = None
            try:
                fit_row, model, beta = fit_one_model(asset, model_variant, device, args)
                params = torch.as_tensor(
                    physical_to_log_phi(
                        {
                            "sigmasq": fit_row["est_sigmasq"],
                            "range_lat": fit_row["est_range_lat"],
                            "range_lon": fit_row["est_range_lon"],
                            "range_time": fit_row["est_range_time"],
                            "advec_lat": fit_row["est_advec_lat"],
                            "advec_lon": fit_row["est_advec_lon"],
                            "nugget": 0.0,
                        }
                    ),
                    device=device,
                    dtype=DTYPE,
                )
                t_diag = time.time()
                curve, diag_summary = conditional_eigen_curve(model, params, beta, args)
                diag_s = time.time() - t_diag
                row = {
                    **fit_row,
                    **diag_summary,
                    "diag_s": float(diag_s),
                }
                print(
                    pd.Series(
                        {
                            "model": row["model_label"],
                            "loss/obs": f"{row['vecchia_loss_per_obs']:.{LOSS_DECIMALS}f}",
                            "conditional_loss/score": f"{row['conditional_loss_per_score']:.{LOSS_DECIMALS}f}",
                            "mean_y2": f"{row['mean_y2']:.5f}",
                            "D": f"{row['max_abs_bridge_scaled']:.5f}",
                            "n_scores": row["n_conditional_scores"],
                            "diag_s": f"{diag_s:.1f}",
                        }
                    ).to_string(),
                    flush=True,
                )
                if args.save_daily_curves:
                    curve_path = out_dir / "daily_curves" / f"year_{asset.year}" / f"sim_{asset.year}_day{asset.day_idx + 1:02d}_{model_variant}_conditional_eig_curve.csv"
                    curve_path.parent.mkdir(parents=True, exist_ok=True)
                    curve.round(ROUND_DECIMALS).to_csv(curve_path, index=False, float_format=f"%.{ROUND_DECIMALS}f")
                day_curves[model_variant] = curve
                avg_rows.append(
                    resample_curve(curve, int(args.resample_grid)).assign(
                        year=int(asset.year),
                        month=int(asset.month),
                        day_idx=int(asset.day_idx),
                        day=str(asset.day_label),
                        model_variant=str(model_variant),
                    )
                )
            except Exception as exc:
                row = {
                    "status": "error",
                    "error": f"{type(exc).__name__}: {exc}",
                    "traceback": traceback.format_exc(limit=12),
                    "year": int(asset.year),
                    "month": int(asset.month),
                    "day_idx": int(asset.day_idx),
                    "day": str(asset.day_label),
                    "model_variant": str(model_variant),
                }
                print(f"ERROR for {model_variant}: {row['error']}", flush=True)
                traceback.print_exc()
            finally:
                if model is not None:
                    del model
                gc.collect()
                if device.type == "cuda":
                    torch.cuda.empty_cache()
            summary_rows.append(clean_json_value(row))
            day_summary_rows.append(clean_json_value(row))
            save_summary(summary_rows, out_dir)

        if day_curves:
            plot_daily_comparison(
                day_curves,
                day_summary_rows,
                out_dir / "daily_plots" / f"year_{asset.year}" / f"sim_{asset.year}_day{asset.day_idx + 1:02d}_vecchia_conditional_eig_comparison.png",
                f"Sim July {asset.year} day_idx={asset.day_idx} ({asset.day_label}): Vecchia conditional eigen diagnostic",
            )

        # Keep monthly plots current after each completed day.
        for year in sorted({int(r.get("year")) for r in summary_rows if r.get("status") == "ok"}):
            year_avg = [df for df in avg_rows if not df.empty and int(df["year"].iloc[0]) == year]
            year_summary = [r for r in summary_rows if r.get("status") == "ok" and int(r.get("year")) == year]
            write_monthly_outputs(year_avg, year_summary, out_dir, year)

    summary = save_summary(summary_rows, out_dir)
    print("\nDone.", flush=True)
    print("summary:", out_dir / f"{RUN_STEM}_summary.csv", flush=True)
    print("ok rows:", int((summary["status"] == "ok").sum()) if not summary.empty and "status" in summary.columns else 0, flush=True)


if __name__ == "__main__":
    main()
